# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 01:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_auto_20170102_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('stage_in_process', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'people'},
        ),
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='linkedin_profile',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='suffix',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='social_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='matcher.Person'),
        ),
        migrations.AddField(
            model_name='match',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='matcher.Position'),
        ),
    ]
