# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0006_auto_20170103_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
