# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0007_position_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='match')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('scheduled_time', models.DateTimeField(blank=True)),
                ('candidate_feedback', models.TextField(blank=True, max_length=1000)),
                ('client_feedback', models.TextField(blank=True, max_length=1000)),
                ('interview_with', models.ManyToManyField(to='matcher.Person')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matcher.Match')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
