# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0008_interview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interview',
            options={'ordering': ('-scheduled_time',)},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
    ]
