# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0009_auto_20170115_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='name',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='position',
            old_name='description',
            new_name='ext_description',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='match',
            name='slug',
        ),
        migrations.AddField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('INP', 'In Person'), ('TEL', 'Telephone'), ('FTS', 'FaceTime/Skype')], default='INP', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='prefix',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='person',
            name='title_code',
            field=models.CharField(choices=[('CFVP', 'CFO/VP Finance'), ('CAAM', 'Controller/Accounting Manager'), ('ACCT', 'Accountant/Sr. Accountant'), ('FINM', 'Finance Manager/Director'), ('FINS', 'Financial Analyst'), ('COST', 'Cost Accountant'), ('TRSY', 'Treasury Positions'), ('ACPY', 'Accounts Payable'), ('AUDT', 'Audit/Audit Manager/Director'), ('TAXA', 'Tax Analyst/Senior'), ('TAXM', 'Tax Manager/Director/VP'), ('RCTR', 'Recruiter'), ('HRPR', 'Human Resources/Payroll')], default='HRPR', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interview',
            name='candidate_feedback',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='interview',
            name='client_feedback',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='match',
            name='stage_in_process',
            field=models.CharField(choices=[('MTCH', 'Matched to Job'), ('SBMT', 'Submitted to Client'), ('RINT', 'Interview Requested'), ('INTP', 'In Interview Process'), ('OFFR', 'Offer Made'), ('PLCD', 'Placement Made'), ('DCLN', 'Candidate Declined'), ('NSFO', 'No Start/Falloff')], max_length=4),
        ),
        migrations.AlterField(
            model_name='position',
            name='salary_lower',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='position',
            name='salary_upper',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='position',
            name='title_code',
            field=models.CharField(choices=[('CFVP', 'CFO/VP Finance'), ('CAAM', 'Controller/Accounting Manager'), ('ACCT', 'Accountant/Sr. Accountant'), ('FINM', 'Finance Manager/Director'), ('FINS', 'Financial Analyst'), ('COST', 'Cost Accountant'), ('TRSY', 'Treasury Positions'), ('ACPY', 'Accounts Payable'), ('AUDT', 'Audit/Audit Manager/Director'), ('TAXA', 'Tax Analyst/Senior'), ('TAXM', 'Tax Manager/Director/VP'), ('RCTR', 'Recruiter'), ('HRPR', 'Human Resources/Payroll')], max_length=30),
        ),
    ]
